services:
  app:
    volumes:
      - .:/var/www/html
    # not needed on prod, composer install - inside docker image
    command: sh -c "composer install --no-interaction && chmod -R 777 storage bootstrap/cache && php-fpm"

  horizon:
    volumes:
      - .:/var/www/html

  nginx:
    volumes:
      - ./public:/var/www/html/public:ro
